### ISSUE TITLE
AppRegistryNotReady with Django 1.9

### ISSUE THREAD

**Issue by mjnaderi** [django-notifications/django-notifications#109]
I use Django 1.9 and django-notifications-hq 0.8.0. When I run `python manage.py runserver`, it raises this exception. When I remove `notifications` from `INSTALLED_APPS`, the exception goes away.

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/me/myproject/.venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/home/me/myproject/.venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/me/myproject/.venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 176, in fetch_command
    commands = get_commands()
  File "/home/me/myproject/.venv/lib/python2.7/site-packages/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/home/me/myproject/.venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 71, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "/home/me/myproject/.venv/lib/python2.7/site-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/home/me/myproject/.venv/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by yangyubo** [comment]
@mjnaderi The master is Django 1.9 compatible but not yet released.

I suggest you use master for now, and waiting next version to be released.

For more info about next release: #89

**Comment by mjnaderi** [comment]
@yangyubo  Thanks.

When I install from master, it raises this exception:

```
Traceback (most recent call last):
  File "/home/me/myproject/.venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/me/myproject/.venv/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check_migrations()
  File "/home/me/myproject/.venv/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 163, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/me/myproject/.venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/me/myproject/.venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/me/myproject/.venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 170, in build_graph
    self.load_disk()
  File "/home/me/myproject/.venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 105, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/me/myproject/.venv/lib/python2.7/site-packages/notifications/migrations/0004_auto_20150826_1508.py", line 8, in <module>
    class Migration(migrations.Migration):
  File "/home/me/myproject/.venv/lib/python2.7/site-packages/notifications/migrations/0004_auto_20150826_1508.py", line 18, in Migration
    field=models.DateTimeField(default=notifications.models.now),
AttributeError: 'module' object has no attribute 'now'
```

**Comment by yangyubo** [comment]
@mjnaderi Good catch! It should has been fixed in master now.
