### ISSUE TITLE
django.db.utils.OperationalError: no such table: notifications_notification

### ISSUE THREAD

**Issue by zzm88** [django-notifications/django-notifications#145]
`C:\FairyBBS>py -2 manage.py migrate notifications`

C:\Python27\lib\site-packages\south\modelsinspector.py:20: RemovedInDjango19Warn
Its contents have been moved to the fields, forms, and admin submodules of djang
  from django.contrib.contenttypes import generic

Operations to perform:
  Apply all migrations: notifications
Running migrations:
  No migrations to apply.
The following content types are stale and need to be deleted:

```
notifications | noticesetting
notifications | noticetype
notifications | noticequeuebatch
```

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

```
Type 'yes' to continue, or 'no' to cancel: yes
```

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management__init__.py", line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management__init__.py", line
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 393,
    self.execute(_args, *_cmd_options)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 444,
    output = self.handle(_args, *_options)
  File "C:\Python27\lib\site-packages\django\core\management\commands\migrate.py
    emit_post_migrate_signal(created_models, self.verbosity, self.interactive, c
  File "C:\Python27\lib\site-packages\django\core\management\sql.py", line 280,
    using=db)
  File "C:\Python27\lib\site-packages\django\dispatch\dispatcher.py", line 201,
    response = receiver(signal=self, sender=sender, **named)
  File "C:\Python27\lib\site-packages\django\contrib\contenttypes\management.py"
    ct.delete()
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 896, in de
    collector.delete()
  File "C:\Python27\lib\site-packages\django\db\models\deletion.py", line 292, i
    qs._raw_delete(using=self.using)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 549, in _
    sql.DeleteQuery(self.model).delete_qs(self, using)
  File "C:\Python27\lib\site-packages\django\db\models\sql\subqueries.py", line
    self.get_compiler(using).execute_sql(NO_RESULTS)
  File "C:\Python27\lib\site-packages\django\db\models\sql\compiler.py", line 84
    cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 79, in
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 64, in
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 64, in
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\sqlite3\base.py", line
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: notifications_notification

**Comment by LegoStormtroopr** [comment]
Django South was deprecated a long time ago, pre django 1.6.

Can you try with a more up-to-date version of Django?

**Comment by bnisevic** [comment]
I get similar on Django 1.10. I have fresh install and when I try to run migration I get:

`Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/.virtualenvs/Giivx/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/.virtualenvs/Giivx/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/.virtualenvs/Giivx/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/.virtualenvs/Giivx/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/.virtualenvs/Giivx/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/.virtualenvs/Giivx/lib/python3.5/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/.virtualenvs/Giivx/lib/python3.5/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/.virtualenvs/Giivx/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/.virtualenvs/Giivx/lib/python3.5/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/.virtualenvs/Giivx/lib/python3.5/site-packages/django/db/migrations/operations/fields.py", line 204, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/home/.virtualenvs/Giivx/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 495, in alter_field
    old_db_params, new_db_params, strict)
  File "/home/.virtualenvs/Giivx/lib/python3.5/site-packages/django/db/backends/postgresql/schema.py", line 117, in _alter_field
    new_db_params, strict,
  File "/home/.virtualenvs/Giivx/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 649, in _alter_field
    params,
  File "/home/.virtualenvs/Giivx/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 112, in execute
    cursor.execute(sql, params)
  File "/home/.virtualenvs/Giivx/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/.virtualenvs/Giivx/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/.virtualenvs/Giivx/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/.virtualenvs/Giivx/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/.virtualenvs/Giivx/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "notifications_notification" does not exist
`

**Comment by bnisevic** [comment]
I figured out what was my problem. I had previously pinax-notifications installed. And its records in the DB mess up things with django-notifications-hq.
So, in order to fix this issue @zzm88 you have to remove all references of pinax-notifications/notifications in django_content_type and django_migrations then run migrations again and it should work.
