### ISSUE TITLE
Testing Live Updater

### ISSUE THREAD

**Issue by SamsadSajid** [django-notifications/django-notifications#196]
In the Readme (https://github.com/django-notifications/django-notifications/#testing-the-live-updater), it is mentioned that to test the live updater I have to

>  export  NOTIFICATION_TEST=1

The whole step was given as this:

> Set the 'NOTIFICATION_TEST' environment variable. E.g. export NOTIFICATION_TEST=1

Where should I export it?
I cloned the repo but couldn' execute the command `./manage.py runserver`
I got the following error:
`Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 62, in execute
    super(Command, self).execute(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 73, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 39, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DEBUG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
`

**Comment by AlvaroLQueiroz** [comment]
You must export the variable in the terminal or pass as parameter when you run the server, like this: **python manage.py runserver test**.

**Comment by SamsadSajid** [comment]
Now I get this error:
`CommandError: "test" is not a valid port number or address:port pair.`

**Comment by AlvaroLQueiroz** [comment]
In the terminal execute: **export NOTIFICATION_TEST=1**
after that, execute: **python manage.py runserver**
