### ISSUE TITLE
Not working on Django 2.2.7?

### ISSUE THREAD

**Issue by renziyao** [django-notifications/django-notifications#274]
When i try to run server with `python3 manage.py runserver`, i got an error. 
```Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x108b71bf8>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'notifications'
```
Environment: `Python 3.7.1` and `Django2.2.7`
Install process of notifications: 
```
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting django-notifications-hq
  Using cached https://mirrors.aliyun.com/pypi/packages/d5/77/e4656cf884593c8e8e046e8dc4b3eb380a7dbfa016f1fcf96832a63b0525/django_notifications_hq-1.5.0-py2.py3-none-any.whl
Requirement already satisfied: jsonfield>=1.0.3 in /usr/local/lib/python3.7/site-packages (from django-notifications-hq) (2.0.2)
Requirement already satisfied: django>=1.7 in /usr/local/lib/python3.7/site-packages (from django-notifications-hq) (2.2.7)
Requirement already satisfied: django-model-utils>=2.0.3 in /usr/local/lib/python3.7/site-packages (from django-notifications-hq) (4.0.0)
Requirement already satisfied: pytz in /usr/local/lib/python3.7/site-packages (from django-notifications-hq) (2019.3)
Requirement already satisfied: sqlparse in /usr/local/lib/python3.7/site-packages (from django>=1.7->django-notifications-hq) (0.3.0)
Installing collected packages: django-notifications-hq
Successfully installed django-notifications-hq-1.5.0
```

**Comment by renziyao** [comment]
Solved. 
MacOS will install the package to python2 even if i execute `pip3 install django-notifications-hq`
run `python3 -m pip install django-notifications-hq` instead.
