### ISSUE TITLE
django-notifications breaks in django 1.11 TypeError: from_db_value() takes 4 positional arguments but 5 were given.

### ISSUE THREAD

**Issue by kirankumbhar** [django-notifications/django-notifications#276]
Hi, recently we faced issue with django notifications on django 1.11. 
While reading notifications using queryset: `models.Notification.objects.filter(recipient=request.user)`,

we got TypeError as `TypeError: from_db_value() takes 4 positional arguments but 5 were given.`

Please note that I'm able to create new notifications, the only issue is while reading notifications using above queryset. I have tried changing queryset with `.all()` and other filter options. But no luck.

Here are the details about environments:
Django==1.11.1
django-model-utils==3.2.0
Python==3.6
PostgreSQL==12.1

Possible Root Cause:
I have looked into django-model-utils dependency. and Probably the error is causing because while installing django-notifications it is fetching django-model-utils==4.0 instead of 3.2. 
As django-model-utils 4.0 have dropped support for django 1.11 it might causing an error.

Please find attached traceback for refrence puprpose:

> Traceback (most recent call last):
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
  response = get_response(request)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 140, in __call__
  response = self.get_response(request)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 43, in inner
  response = response_for_exception(request, exc)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
  response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 143, in handle_uncaught_exception
  return callback(request, **param_dict)
File "/opt/python/bundle/4/app/core/views.py", line 47, in error_500
  return render(request, '500.html')
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
  content = loader.render_to_string(template_name, context, request, using=using)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/template/loader.py", line 68, in render_to_string
  return template.render(context, request)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
  return self.template.render(context)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/template/base.py", line 207, in render
  return self._render(context)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
  return self.nodelist.render(context)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/template/base.py", line 990, in render
  bit = node.render_annotated(context)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
  return self.render(context)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
  return compiled_parent._render(context)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
  return self.nodelist.render(context)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/template/base.py", line 990, in render
  bit = node.render_annotated(context)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
  return self.render(context)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 72, in render
  result = block.nodelist.render(context)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/template/base.py", line 990, in render
  bit = node.render_annotated(context)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
  return self.render(context)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 322, in render
  return nodelist.render(context)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/template/base.py", line 990, in render
  bit = node.render_annotated(context)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
  return self.render(context)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 173, in render
  len_values = len(values)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/query.py", line 232, in __len__
  self._fetch_all()
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/query.py", line 1103, in _fetch_all
  self._result_cache = list(self._iterable_class(self))
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/query.py", line 62, in __iter__
  for row in compiler.results_iter(results):
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 834, in results_iter
  row = self.apply_converters(row, converters)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 819, in apply_converters
  value = converter(value, expression, self.connection, self.query.context)
 TpeError: from_db_value() takes 4 positional arguments but 5 were given

**Comment by vpanga** [comment]
Hi Kiran, I experienced the same issue.
Resolved the issue with [django-notifications==1.5.0] which is compatible with django 1.11.

**Comment by nemesisdesign** [comment]
We don't have the resources to support such old django versions.
You either have to upgrade or patch it yourself.
