### ISSUE TITLE
Conflict model when create custom Notification inherit from AbstractNotification.

### ISSUE THREAD

**Issue by dphans** [django-notifications/django-notifications#282]
Like document purpose, I already need to add category to filter notification based on category but when I create custom class inherit form AbstractNotification, django raise exceptions...

```
# models.py

from django.db import models
from django.utils.translation import gettext_lazy as _
from notifications.base.models import AbstractNotification


class Notification(AbstractNotification):
    class Meta(AbstractNotification.Meta):
        abstract = False

    CHOICES_CATEGORY_EVENT = 'EVENT'
    CHOICES_CATEGORY_WORK = 'WORK'
    CHOICES_CATEGORY_COMMENT = 'COMMENT'
    CHOICES_CATEGORY_URGENT = 'URGENT'
    CHOICES_CATEGORY_COMPANY = 'COMPANY'
    CHOICES_CATEGORIES = (
        (CHOICES_CATEGORY_EVENT, _('Event')),
        (CHOICES_CATEGORY_WORK, _('Work')),
        (CHOICES_CATEGORY_COMMENT, _('Comment')),
        (CHOICES_CATEGORY_URGENT, _('Urgent')),
        (CHOICES_CATEGORY_COMPANY, _('Company')),
    )

    category = models.CharField(
        max_length=63,
        choices=CHOICES_CATEGORIES,
        default=None,
        null=True,
        blank=True,
    )
```

Exception from terminal:
```
bootstrap_django_dev | Exception in thread django-main-thread:
bootstrap_django_dev | Traceback (most recent call last):
bootstrap_django_dev |   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
bootstrap_django_dev |     self.run()
bootstrap_django_dev |   File "/usr/local/lib/python3.7/threading.py", line 870, in run
bootstrap_django_dev |     self._target(*self._args, **self._kwargs)
bootstrap_django_dev |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
bootstrap_django_dev |     fn(*args, **kwargs)
bootstrap_django_dev |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
bootstrap_django_dev |     autoreload.raise_last_exception()
bootstrap_django_dev |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
bootstrap_django_dev |     raise _exception[1]
bootstrap_django_dev |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
bootstrap_django_dev |     autoreload.check_errors(django.setup)()
bootstrap_django_dev |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
bootstrap_django_dev |     fn(*args, **kwargs)
bootstrap_django_dev |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
bootstrap_django_dev |     apps.populate(settings.INSTALLED_APPS)
bootstrap_django_dev |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
bootstrap_django_dev |     app_config.import_models()
bootstrap_django_dev |   File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
bootstrap_django_dev |     self.models_module = import_module(models_module_name)
bootstrap_django_dev |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
bootstrap_django_dev |     return _bootstrap._gcd_import(name[level:], package, level)
bootstrap_django_dev |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
bootstrap_django_dev |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
bootstrap_django_dev |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
bootstrap_django_dev |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
bootstrap_django_dev |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
bootstrap_django_dev |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
bootstrap_django_dev |   File "/usr/src/dev/django/master/streams/models.py", line 5, in <module>
bootstrap_django_dev |     class Notification(AbstractNotification):
bootstrap_django_dev |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 320, in __new__
bootstrap_django_dev |     new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
bootstrap_django_dev |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 229, in register_model
bootstrap_django_dev |     (model_name, app_label, app_models[model_name], model))
bootstrap_django_dev | RuntimeError: Conflicting 'notification' models in application 'notifications': <class 'notifications.models.Notification'> and <class 'master.streams.models.Notification'>.
```

**Comment by TheOneAboveAllTitan** [comment]
Did you updated your `settings.py` to trigger `swapper`?

**Comment by TheOneAboveAllTitan** [comment]
You will need to define `app_label` in `Notification` model, since `app_label` is defined in `AbstractNotificatio.Meta` so you will have to explicitly define that. It should will be fixed in #284 

```
class Notification(AbstractNotification):
    class Meta(AbstractNotification.Meta):
        abstract = False
        app_label = 'your_application_name' 
```

**Comment by TheOneAboveAllTitan** [comment]
@dphans  @nemesisdesign I think this can be closed now, :smile:

**Comment by begimai** [comment]
@pandafy can you tell more on customizations of Notification Model? 
makemigrations does not detect changes

**Comment by pandafy** [comment]
@begimai have referred to documentation for extending Notification's model? 
You can have a look here: https://github.com/django-notifications/django-notifications#abstractnotification-model

**Comment by begimai** [comment]
yes I followed the documents, but migrations would not see changes.
-extended in my notification app's models.py,
-added settings attribute,

Perhaps it is because original Notification model already existed?
or my internal app's name is the same? 
what steps would you suggest to take?

**Comment by pandafy** [comment]
The original Notification model is swappable, if you have configured  `NOTIFICATIONS_NOTIFICATION_MODEL` settings properly, it should work flawlessly. There is an example usage given in sample app. 

https://github.com/django-notifications/django-notifications/blob/master/notifications/tests/sample_notifications/models.py

**Comment by rafaelJerbi** [comment]
I followed all instructions, but still having the same issue.
any suggestions?

**Comment by nemesisdesign** [comment]
Look at the test project of [openwisp-notifications](https://github.com/openwisp/openwisp-notifications/) for a reference implementation.

**Comment by luoruiqing** [comment]
> settings.py 
NOTIFICATIONS_NOTIFICATION_MODEL = 'sso.models.notify.Notification'

case1: 

```py
class Notification(AbstractNotification):

    config = JSONField(blank=True, null=True)
    process = JSONField(blank=True, null=True)

    class Meta(AbstractNotification.Meta):
        abstract = False
```

 RuntimeError: Conflicting 'notification' models in application 'notifications': <class 'notifications.models.Notification'> and <class 'sso.models.notify.Notification'>.

---

case2:

```py
class Notification(AbstractNotification):

    config = JSONField(blank=True, null=True)
    process = JSONField(blank=True, null=True)

    class Meta(AbstractNotification.Meta):
        abstract = False
        app_label = 'sso'  # set app_label
```
command
```sh
./manage.py makemigrations sso
```

No default migration information

```log
Migrations for 'sso':
  sso/migrations/0008_notification.py
    - Create model Notification
```


```py
notify.send(TEST_OBJECT, recipient=request.user, verb='start...', level="info")
# error: django.core.exceptions.ImproperlyConfigured: Could not find sso.models.notify.Notification!
```

**Comment by db4y** [comment]
@luoruiqing in settings.py you should have ` NOTIFICATIONS_NOTIFICATION_MODEL = 'sso.Notification'`

**Comment by luoruiqing** [comment]
> @luoruiqing in settings.py you should have ` NOTIFICATIONS_NOTIFICATION_MODEL = 'sso.Notification'`

thanks~ 😄

**Comment by linhnvhicts** [comment]
can this be updated in the docs? because it doesn't mention you need `app_label`, else you get the error
